import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {createHmac} from 'node:crypto';
import {encryptToken,decryptToken,validBotToken,telegram} from '../../functions/_lib/managed-bot-runtime.js';
import {registerBot,manageBot,ownedBot,rateLimit} from '../../functions/_lib/managed-bot-service.js';
import {enqueue,processJob,recoverJobs,parseCommand} from '../../functions/_lib/managed-bot-jobs.js';
import {portablePage,pagePayload,callbackAction} from '../../functions/_lib/managed-bot-pages.js';
import {acceptLicenseEvent} from '../../functions/_lib/managed-bot-licenses.js';
import {onRequest as ownerApi} from '../../functions/miniapp/api/managed-bots.js';
import {onRequestPost as webhook} from '../../functions/managed-bots/[botKey].js';
import {onRequest as internalApi} from '../../functions/internal/managed-bots.js';
import {transferRichMedia} from '../../functions/_lib/managed-bot-media.js';
import {harness} from './harness.mjs';
const secret='test-only-encryption-material-not-a-real-secret',token='123456:'+ 'x'.repeat(35),otherToken='654321:'+ 'y'.repeat(35);
class D1 {
 constructor(){this.sql=new DatabaseSync(':memory:');this.sql.exec(fs.readFileSync(new URL('../../cloudflare/d1/managed_bots.sql',import.meta.url),'utf8'));this.sql.exec(fs.readFileSync(new URL('../../cloudflare/d1/migrations/0001-managed-bots-runtime.sql',import.meta.url),'utf8'));this.failCompletion=false;}
 prepare(query){const db=this;let args=[];return {query,bind(...a){args=a;return this;},async first(){return db.sql.prepare(query).get(...args)||null;},async all(){return {results:db.sql.prepare(query).all(...args)};},async run(){if(db.failCompletion&&query.includes("status='completed'"))throw Error('simulated disk failure');const r=db.sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}};}};}
 async batch(statements){this.sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());this.sql.exec('COMMIT');return out;}catch(e){this.sql.exec('ROLLBACK');throw e;}}
}
function fixture(t){const env={DB:new D1(),MANAGED_BOT_ENCRYPTION_KEY:secret,MANAGED_BOTS_REGISTRATION_ENABLED:'true',MANAGED_BOTS_PUBLIC_ORIGIN:'https://example.test',BOT_TOKEN:'999999:'+ 'z'.repeat(35),B2B_BOT_TOKEN:'888888:'+ 'r'.repeat(35)};
 const calls=[],hooks=new Map(),faults=new Map(),documents=new Map();const original=globalThis.fetch;
 globalThis.fetch=async(url,options={})=>{const method=String(url).split('/').at(-1),payload=options.body?JSON.parse(options.body):{};if(String(url).includes('/file/'))return Response.json(documents.get(method));const id=String(url).match(/\/bot(\d+):/)?.[1];calls.push({method,payload,id});if(faults.has(method))return faults.get(method)(payload);let result;
 if(method==='getMe')result={id:Number(id),is_bot:true,username:id==='123456'?'testbot':'otherbot',first_name:'Test'};
 else if(method==='getWebhookInfo')result={url:hooks.get(id)||''};else if(method==='setWebhook'){hooks.set(id,payload.url);result=true;}else if(method==='deleteWebhook'){hooks.delete(id);result=true;}
 else if(method==='getFile')result={file_path:payload.file_id};else if(method==='getChat')result={id:payload.chat_id,type:'channel'};else if(method==='getChatMember')result={status:'administrator',can_post_messages:true};
 else result={message_id:100+calls.length,chat:{id:payload.chat_id}};
 return Response.json({ok:true,result});};t.after(()=>{globalThis.fetch=original;env.DB.sql.close();});
 function license(id='license_001',owner='1',expires=Date.now()+86400000){env.DB.sql.prepare("INSERT INTO managed_bot_licenses VALUES(?,?,'active',?,1,?,?)").run(id,String(owner),expires,'event_'+id,Date.now());}
 async function bot(id='license_001',owner='1',tok=token){license(id,owner);const {bot}=await registerBot(env,owner,{token:tok,license_id:id});return ownedBot(env,owner,bot.id);}
 async function activate(b){await manageBot(env,b.owner_id,{id:b.id,action:'activate',confirm:true,confirmWebhookTakeover:true});return ownedBot(env,b.owner_id,b.id);}
 return {env,calls,hooks,faults,documents,license,bot,activate};}
function auth(env,id=1){const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id})});const data=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');const key=createHmac('sha256','WebAppData').update(env.BOT_TOKEN).digest();p.set('hash',createHmac('sha256',key).update(data).digest('hex'));return p.toString();}
function ownerContext(env,body,id=1){return {env,request:new Request('https://example.test/miniapp/api/managed-bots',{method:'POST',headers:{'X-Telegram-Init-Data':auth(env,id)},body:JSON.stringify(body)})};}
async function seedPage(f,job,pageId='page-one',owner=1){
 const db=f.env.DB.sql;db.exec(`CREATE TABLE IF NOT EXISTS miniapp_bridge_pending(request_id TEXT PRIMARY KEY,user_id INTEGER,action TEXT,page_id TEXT,status TEXT,response_kind TEXT,response_file_id TEXT,response_json TEXT,error_code TEXT,error_message TEXT,created_at INTEGER,expires_at INTEGER,completed_at INTEGER);CREATE TABLE IF NOT EXISTS miniapp_bridge_identity(key TEXT PRIMARY KEY,value TEXT,updated_at INTEGER);CREATE TABLE IF NOT EXISTS miniapp_bridge_gate(key TEXT PRIMARY KEY,next_send_at_ms INTEGER,open_until_ms INTEGER,consecutive_failures INTEGER,minute_bucket INTEGER,minute_count INTEGER,updated_at_ms INTEGER);CREATE TABLE IF NOT EXISTS miniapp_bridge_metrics(minute INTEGER PRIMARY KEY,queued INTEGER,sent INTEGER,deduped INTEGER,rate_limited INTEGER,rejected INTEGER,failed INTEGER);`);
 const rid='request_'+job.job_id.replaceAll(':','_'),payload={protocol:'RCB1',action:'managed_page',request_id:rid,user_id:owner,owner_id:owner,page_id:pageId,rich_message:{blocks:[{type:'paragraph',text:'مرحبا'}]},buttons:[],buttons_per_row:1};
 db.prepare("INSERT INTO miniapp_bridge_pending(request_id,user_id,action,page_id,status,response_kind,response_file_id,created_at,expires_at) VALUES(?,?,'managed_page',?,'ready','document',?,?,?)").run(rid,owner,pageId,rid,Math.floor(Date.now()/1000),Math.floor(Date.now()/1000)+300);db.prepare('UPDATE managed_bot_jobs SET bridge_request_id=? WHERE bot_id=? AND job_id=?').run(rid,job.bot_id,job.job_id);f.documents.set(rid,payload);return {rid,payload};
}
test('token validation, randomized authenticated encryption and wrong-key/tamper rejection',async()=>{assert(validBotToken(token));assert(!validBotToken('invalid'));const a=await encryptToken(token,secret),b=await encryptToken(token,secret);assert.notEqual(a,b);assert(!a.includes(token));assert.equal(await decryptToken(a,secret),token);await assert.rejects(()=>decryptToken(a,secret+'wrong'));const c=JSON.parse(a);c.data='ff'+c.data.slice(2);await assert.rejects(()=>decryptToken(JSON.stringify(c),secret));});
test('registration is licensed, atomic under contention and never changes a webhook',async t=>{const f=fixture(t);await assert.rejects(()=>registerBot(f.env,'1',{token,license_id:'none'}),/license_required/);f.license();const results=await Promise.allSettled([registerBot(f.env,'1',{token,license_id:'license_001'}),registerBot(f.env,'1',{token:otherToken,license_id:'license_001'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.env.DB.sql.prepare('SELECT COUNT(*) n FROM managed_bots').get().n,1);assert(!f.calls.some(c=>c.method==='setWebhook'));assert(!JSON.stringify(results).includes(token));});
test('reject bad getMe, reserved identity, duplicate bot and client entitlement bypass',async t=>{const f=fixture(t);f.license();f.faults.set('getMe',()=>Response.json({ok:false,error_code:401},{status:401}));await assert.rejects(()=>registerBot(f.env,'1',{token,license_id:'license_001'}),/invalid_token/);f.faults.delete('getMe');f.env.MANAGED_BOTS_RESERVED_IDS='123456';await assert.rejects(()=>registerBot(f.env,'1',{token,license_id:'license_001'}),/reserved_bot/);delete f.env.MANAGED_BOTS_RESERVED_IDS;await registerBot(f.env,'1',{token,license_id:'license_001'});f.license('license_002');await assert.rejects(()=>registerBot(f.env,'1',{token,license_id:'license_002'}),/already_linked/);const res=await ownerApi(ownerContext(f.env,{action:'register',token:otherToken,license_id:'license_002',owner_id:1,plan:'active'},2));assert.equal(res.status,403);});
test('owner isolation covers every owner action and anonymous API',async t=>{const f=fixture(t),b=await f.bot();for(const action of ['welcome','activate','disable','rotate_token','unlink','bind_page','publish','job','commands']){const r=await ownerApi(ownerContext(f.env,{action,id:b.id,text:'x',token},2));assert.equal(r.status,404,action);}const r=await ownerApi({env:f.env,request:new Request('https://example.test')});assert.equal(r.status,401);});
test('activation requires confirmation and takeover confirmation; disable preserves external webhook',async t=>{const f=fixture(t),b=await f.bot();f.hooks.set('123456','https://external.test/hook');const check=await manageBot(f.env,'1',{action:'activate',id:b.id});assert.equal(check.external_webhook,true);await assert.rejects(()=>manageBot(f.env,'1',{action:'activate',id:b.id,confirm:true}),/takeover/);await f.activate(b);assert(f.hooks.get('123456').startsWith('https://example.test/managed-bots/'));await manageBot(f.env,'1',{action:'disable',id:b.id,confirm:true});assert(!f.hooks.has('123456'));await f.activate(b);f.hooks.set('123456','https://new-external.test');await manageBot(f.env,'1',{action:'disable',id:b.id,confirm:true});assert.equal(f.hooks.get('123456'),'https://new-external.test');});
test('token rotation checks same identity, encrypts new credential and requires reactivation',async t=>{const f=fixture(t),b=await f.activate(await f.bot());await assert.rejects(()=>manageBot(f.env,'1',{action:'rotate_token',id:b.id,confirm:true,token:otherToken}),/identity_mismatch/);const next='123456:'+ 'n'.repeat(35);await manageBot(f.env,'1',{action:'rotate_token',id:b.id,confirm:true,token:next});const current=await ownedBot(f.env,'1',b.id);assert.equal(current.status,'disabled');assert.equal(await decryptToken(current.token_encrypted,secret),next);assert.notEqual(current.webhook_secret,b.webhook_secret);});
test('valid webhook sends start, rejects unauthenticated updates, deduplicates and isolates bots',async t=>{const f=fixture(t),b=await f.activate(await f.bot()),b2=await f.activate(await f.bot('license_002','2',otherToken));async function send(bot,sec){return webhook({env:f.env,params:{botKey:bot.webhook_key},request:new Request('https://example.test',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':sec},body:JSON.stringify({update_id:1,message:{chat:{id:7,type:'private'},from:{id:7},text:'/start hello'}})})});}assert.equal((await send(b,'wrong')).status,401);assert.equal((await send(b,b.webhook_secret)).status,200);await send(b,b.webhook_secret);await send(b2,b2.webhook_secret);assert.equal(f.calls.filter(c=>c.method==='sendMessage').length,2);assert.deepEqual(f.calls.filter(c=>c.method==='sendMessage').map(c=>c.id),['123456','654321']);assert.equal(parseCommand('/start\nhello','testbot'),'/start');assert.equal(parseCommand('/start@otherbot','testbot'),'');});
test('admin is owner-only; groups receive help; channel posts do not trigger reply loops',async t=>{const f=fixture(t),b=await f.activate(await f.bot());for(const [i,actor] of [1,2].entries()){const j=await enqueue(f.env,b,'u:'+i,{kind:'update',update:{message:{chat:{id:actor,type:'private'},from:{id:actor},text:'/admin'}}});await processJob({env:f.env},b.id,j.job_id);}const sends=f.calls.filter(c=>c.method==='sendMessage');assert.match(sends[0].payload.text,/إدارة بوتك/);assert.match(sends[1].payload.text,/مخصص/);const j=await enqueue(f.env,b,'u:9',{kind:'update',update:{channel_post:{chat:{id:-1,type:'channel'},text:'/start'}}});await processJob({env:f.env},b.id,j.job_id);assert.equal(f.calls.filter(c=>c.method==='sendMessage').length,2);});
test('expiry suspends runtime and refuses activation without losing settings',async t=>{const f=fixture(t),b=await f.activate(await f.bot());await manageBot(f.env,'1',{id:b.id,action:'welcome',text:'welcome'});f.env.DB.sql.prepare('UPDATE managed_bot_licenses SET expires_at=0').run();await assert.rejects(()=>f.activate(b),/license_required/);const j=await enqueue(f.env,b,'u:1',{kind:'update',update:{message:{chat:{id:1,type:'private'},text:'/start'}}});assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'suspended');assert.equal((await ownedBot(f.env,'1',b.id)).welcome_text,'welcome');});
test('confirmed 429 retries; ambiguous network delivery and post-send DB failure never auto-resend',async t=>{const f=fixture(t),b=await f.activate(await f.bot());const payload={kind:'update',update:{message:{chat:{id:1,type:'private'},text:'/start'}}};let j=await enqueue(f.env,b,'u:1',payload);f.faults.set('sendMessage',()=>Response.json({ok:false,error_code:429,parameters:{retry_after:1}},{status:429}));assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'pending');f.faults.delete('sendMessage');f.env.DB.sql.prepare('UPDATE managed_bot_jobs SET next_attempt_at=0').run();assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'completed');j=await enqueue(f.env,b,'u:2',payload);f.faults.set('sendMessage',()=>{throw Error('network '+token);});assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'uncertain');f.faults.delete('sendMessage');j=await enqueue(f.env,b,'u:3',payload);f.env.DB.failCompletion=true;assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'uncertain');f.env.DB.failCompletion=false;const count=f.calls.filter(c=>c.method==='sendMessage').length;await recoverJobs({env:f.env});assert.equal(f.calls.filter(c=>c.method==='sendMessage').length,count);});
test('stale processing recovers; stale sends quarantine and operations suspend for review',async t=>{const f=fixture(t),b=await f.activate(await f.bot()),j=await enqueue(f.env,b,'u:1',{kind:'update',update:{message:{chat:{id:1,type:'private'},text:'/start'}}});f.env.DB.sql.prepare("UPDATE managed_bot_jobs SET status='processing',lease_until=0").run();await recoverJobs({env:f.env});assert.equal(f.env.DB.sql.prepare('SELECT status FROM managed_bot_jobs').get().status,'completed');f.env.DB.sql.prepare("UPDATE managed_bot_jobs SET status='sending',lease_until=0").run();f.env.DB.sql.prepare('UPDATE managed_bots SET operation_key=?,operation_at=1').run('stale');await recoverJobs({env:f.env});assert.equal(f.env.DB.sql.prepare('SELECT status FROM managed_bot_jobs').get().status,'uncertain');assert.equal((await ownedBot(f.env,'1',b.id)).status,'suspended');});
test('rich page rendered by existing engine is owner-scoped, unbranded and keeps blocks',async()=>{const h=await harness({extraModules:{managed:'lib/managed-pages'}});h.records.richPages.push({pageId:'p',ownerId:1,blocks:[{type:'paragraph',data:{text:'Hello'}},{type:'heading',data:{text:'Title'}}],buttons:[]});const page=await h.managed.managedPage(1,'p');assert.equal(page.rich_message.blocks.length,2);assert(!JSON.stringify(page).includes('RichCustomizebot'));await assert.rejects(()=>h.managed.managedPage(2,'p'),/PAGE_NOT_FOUND/);});
test('bind and send real rich payload through owner API, maintain publication and reject foreign page',async t=>{const f=fixture(t),b=await f.activate(await f.bot());let j=await enqueue(f.env,b,'p:abcdefghijklmnop',{kind:'publish',page_id:'page-one',chat_id:1});const {rid,payload}=await seedPage(f,j);const res=await ownerApi(ownerContext(f.env,{action:'bind_page',id:b.id,page_id:'page-one',request_id:rid}));assert.equal(res.status,200,await res.text());assert.equal((await ownedBot(f.env,'1',b.id)).welcome_page_id,'page-one');assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'completed');const sent=f.calls.find(c=>c.method==='sendRichMessage');assert.equal(sent.id,'123456');assert.deepEqual(sent.payload.rich_message,payload.rich_message);assert.equal(f.env.DB.sql.prepare('SELECT COUNT(*) n FROM managed_bot_publications').get().n,1);payload.owner_id=2;assert.equal((await ownerApi(ownerContext(f.env,{action:'bind_page',id:b.id,page_id:'page-one',request_id:rid}))).status,502);});
test('media rejection and inline/rich callback fallback preserve URL/copy buttons',()=>{const p={rich_message:{blocks:[{type:'paragraph',text:'ok'}]},buttons:[{type:'url',text:'link',value:'https://example.test'},{type:'copy',text:'copy',value:'x'},{type:'callback_data',text:'action',value:'old:data'},{type:'popup',text:'popup',value:'Hello'}]};assert.equal(pagePayload(p,1).reply_markup.inline_keyboard[2][0].callback_data,'old:data');assert.deepEqual(callbackAction(p,'mb:popup:3'),{text:'Hello'});assert.deepEqual(callbackAction(p,'old:data'),{text:'تم استلام طلبك.'});assert.throws(()=>portablePage({rich_message:{blocks:[{type:'photo',photo:{file_id:'main-bot-file-id'}}]}}),/media_reupload_required/);});
test('unlink cancels pending work and removes secrets but keeps license available',async t=>{const f=fixture(t),b=await f.activate(await f.bot());await enqueue(f.env,b,'u:1',{kind:'update',update:{}});await manageBot(f.env,'1',{action:'unlink',id:b.id,confirm:true});assert.equal(f.env.DB.sql.prepare('SELECT COUNT(*) n FROM managed_bots').get().n,0);assert.equal(f.env.DB.sql.prepare('SELECT status FROM managed_bot_jobs').get().status,'cancelled');assert.equal(f.env.DB.sql.prepare('SELECT COUNT(*) n FROM managed_bot_licenses').get().n,1);});
test('license adapter disabled by default, signature verified, replay idempotent and stale events cannot extend',async t=>{const f=fixture(t),event={event_id:'event_0001',license_id:'license_001',owner_id:'1',status:'active',expires_at:Date.now()+60000,version:2};f.env.MANAGED_BOTS_LICENSE_KEY=secret;
 const request=e=>{const raw=JSON.stringify(e),ts=String(Date.now());return new Request('https://example.test',{method:'POST',headers:{'X-Managed-Timestamp':ts,'X-Managed-Signature':createHmac('sha256',secret).update(ts+'.'+raw).digest('hex')},body:raw});};await assert.rejects(()=>acceptLicenseEvent(request(event),f.env),/disabled/);f.env.MANAGED_BOTS_LICENSE_PROVIDER_ENABLED='true';await acceptLicenseEvent(request(event),f.env);assert.equal((await acceptLicenseEvent(request(event),f.env)).duplicate,true);await acceptLicenseEvent(request({...event,event_id:'event_old1',version:1,expires_at:Date.now()+900000}),f.env);assert.equal(f.env.DB.sql.prepare('SELECT expires_at FROM managed_bot_licenses').get().expires_at,event.expires_at);await assert.rejects(()=>acceptLicenseEvent(new Request('https://example.test',{method:'POST',body:JSON.stringify(event)}),f.env),/unauthorized/);});
test('rate limits are atomic and internal API cannot register without trusted owner',async t=>{const f=fixture(t);await rateLimit(f.env.DB,'test',1);await assert.rejects(()=>rateLimit(f.env.DB,'test',1),/rate_limited/);const response=await internalApi({env:f.env,request:new Request('https://example.test',{method:'POST',body:JSON.stringify({action:'register',token,ownerId:1})})});assert.equal(response.status,401);});

test('cross-bot media is downloaded from trusted Telegram source and attached, never reused as file_id',async t=>{
 const original=globalThis.fetch,calls=[];t.after(()=>globalThis.fetch=original);
 globalThis.fetch=async(url,options)=>{calls.push(String(url));if(String(url).endsWith('/getFile'))return Response.json({ok:true,result:{file_path:'photos/file.jpg',file_size:3}});return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'image/jpeg'}});};
 const input={chat_id:1,rich_message:{blocks:[{type:'photo',media:'source_file_id'},{type:'photo',media:'source_file_id'}]}};
 const result=await transferRichMedia({BOT_TOKEN:token},input);assert(result instanceof FormData);assert.equal(calls.length,2);assert.equal(result.get('managed_media_0').size,3);assert(!result.get('rich_message').includes('source_file_id'));assert.match(result.get('rich_message'),/attach:\/\/managed_media_0/);assert.equal(input.rich_message.blocks[0].media,'source_file_id');
});

test('rich /start sends linked page and callback validates published bot/chat/message and revision',async t=>{
 const f=fixture(t),b=await f.activate(await f.bot());f.env.DB.sql.prepare('UPDATE managed_bots SET welcome_page_id=? WHERE id=?').run('page-one',b.id);
 const j=await enqueue(f.env,b,'u:77',{kind:'update',update:{message:{chat:{id:7,type:'private'},text:'/start'}}});const {payload}=await seedPage(f,j);payload.buttons=[{type:'callback_data',text:'Action',value:'old:data'}];
 assert.equal((await processJob({env:f.env},b.id,j.job_id)).status,'completed');
 const pub=f.env.DB.sql.prepare('SELECT * FROM managed_bot_publications').get();assert.equal(pub.chat_id,'7');
 const cb={kind:'update',update:{callback_query:{id:'callback',from:{id:7},data:'old:data',message:{message_id:pub.message_id,chat:{id:7,type:'private'}}}}};
 const next=await enqueue(f.env,b,'u:78',cb);const page=await seedPage(f,next);page.payload.buttons=payload.buttons;
 assert.equal((await processJob({env:f.env},b.id,next.job_id)).status,'completed');assert.equal(f.calls.filter(c=>c.method==='answerCallbackQuery').at(-1).payload.text,'تم استلام طلبك.');
 const foreign=await f.activate(await f.bot('license_002','2',otherToken)),bad=await enqueue(f.env,foreign,'u:78',cb);await processJob({env:f.env},foreign.id,bad.job_id);assert.match(f.calls.filter(c=>c.method==='answerCallbackQuery').at(-1).payload.text,/غير مرتبط/);
});
test('channel publishing checks owner and bot permissions before sending',async t=>{
 const f=fixture(t),b=await f.activate(await f.bot());f.faults.set('getChatMember',()=>Response.json({ok:true,result:{status:'member'}}));
 const j=await enqueue(f.env,b,'p:channeltest00001',{kind:'publish',page_id:'page-one',chat_id:-100});const result=await processJob({env:f.env},b.id,j.job_id);assert.equal(result.status,'failed');assert.equal(result.error,'owner_chat_permission_required');assert(!f.calls.some(c=>c.method==='sendRichMessage'));
});
test('concurrent activate/disable calls cannot race webhook side effects',async t=>{
 const f=fixture(t),b=await f.bot();const results=await Promise.allSettled([f.activate(b),manageBot(f.env,'1',{id:b.id,action:'disable',confirm:true})]);assert.equal(results.filter(x=>x.status==='rejected'&&x.reason.code==='operation_in_progress').length,1);assert.equal(f.calls.filter(c=>['setWebhook','deleteWebhook'].includes(c.method)).length,1);
});
test('pre-existing failed/processing update migration retains evidence and never schedules duplicate sends',()=>{
 const db=new DatabaseSync(':memory:');try{db.exec(fs.readFileSync(new URL('../../cloudflare/d1/managed_bots.sql',import.meta.url),'utf8'));db.prepare("INSERT INTO managed_bots(id,owner_id,bot_telegram_id,webhook_key,webhook_secret,token_encrypted,created_at,updated_at) VALUES('old','1','123','key','secret','encrypted',1,1)").run();db.prepare("INSERT INTO managed_bot_updates VALUES('old',7,'processing',1)").run();db.exec(fs.readFileSync(new URL('../../cloudflare/d1/migrations/0001-managed-bots-runtime.sql',import.meta.url),'utf8'));assert.equal(db.prepare('SELECT token_encrypted FROM managed_bots').get().token_encrypted,'encrypted');assert.equal(db.prepare('SELECT status FROM managed_bot_jobs').get().status,'uncertain');}finally{db.close();}
});
