from __future__ import annotations

import logging

from aiogram import Bot, F, Router
from aiogram.filters import Command
from aiogram.types import CallbackQuery, Message

from app.i18n import t
from app.services.showcase import MissingShowcaseMedia, send_all_blocks_showcase


router = Router(name="editor_showcase")
logger = logging.getLogger(__name__)


async def _send_showcase(bot: Bot, chat_id: int, user_id: int) -> None:
    """Build one Rich Message containing the complete block showcase.

    Textual/demo blocks are generated by the showcase builder while reusable
    media for photo/video/animation/audio/voice blocks comes from the showcase
    media library populated by the configured channel and persisted through the
    normal PostgreSQL/JSON repository.
    """
    await send_all_blocks_showcase(bot, chat_id, user_id)


@router.message(Command("draft"))
@router.message(F.text.in_({"دريفت", "draft", "Draft", "DRAFT"}))
async def showcase_from_message(message: Message, bot: Bot) -> None:
    if not message.from_user:
        return
    await bot.send_chat_action(chat_id=message.chat.id, action="typing")
    try:
        await _send_showcase(bot, message.chat.id, message.from_user.id)
    except MissingShowcaseMedia as error:
        logger.warning(
            "Showcase media library is incomplete for user_id=%s: %s",
            message.from_user.id,
            error,
        )
        await message.answer(t("preview_failed"))
    except Exception:
        logger.exception(
            "Failed to build all-block showcase for user_id=%s",
            message.from_user.id,
        )
        await message.answer(t("preview_failed"))


@router.callback_query(F.data == "r:showcase")
async def showcase_from_button(callback: CallbackQuery, bot: Bot) -> None:
    await callback.answer(t("preview_generating"))
    try:
        await _send_showcase(bot, callback.from_user.id, callback.from_user.id)
    except MissingShowcaseMedia as error:
        logger.warning(
            "Showcase media library is incomplete for user_id=%s: %s",
            callback.from_user.id,
            error,
        )
        await bot.send_message(callback.from_user.id, t("preview_failed"))
    except Exception:
        logger.exception(
            "Failed to build all-block showcase for user_id=%s",
            callback.from_user.id,
        )
        await bot.send_message(callback.from_user.id, t("preview_failed"))


__all__ = [
    "router",
    "showcase_from_button",
    "showcase_from_message",
]
