from __future__ import annotations

from app.locales.common import pack, profile

TRANSLATIONS = {
    "tr": pack(customize="Mesajı özelleştir", choose_block="Düzenlemek istediğin bloğu seç:", block_added="Blok başarıyla eklendi.", welcome="Rich Message Düzenleyicisine hoş geldin.", start_editor="Yeni bir mesaj başlatmak için /editor gönder.", send_message="Özelleştirmek istediğin mesajı gönder.", unsupported="Bu tür desteklenmiyor. Metin, medya veya Rich Message gönder.", expired="Oturum sona erdi. Yeniden başlamak için /editor gönder.", add_block="➕ Blok ekle", result="✅ Sonuç", create_post="📝 Gönderi oluştur", save_page="💾 Sayfayı kaydet", pages="📚 Sayfalarım", edit="✏️ Düzenle", edit_content="✏️ İçeriği düzenle", delete="🗑 Sil", move="↕️ Konumu değiştir", back="🔙 Geri", preview_block="👁 Bu bloğu önizle", preview_generating="Önizleme oluşturuluyor…", preview_ready="Önizleme hazır.", preview_failed="Önizleme başarısız.", add_buttons="🔘 Buton ekle", buttons_manage="Rich Message butonlarını yönet", add="➕ Ekle", remove="➖ Kaldır", color="🎨 Rengi değiştir", reorder="↕️ Sırala", post_settings="Gönderi ayarları", send_now="📤 Gönderiyi şimdi gönder", select_chat="En az bir sohbet seç.", details="Detaylar", photo="Fotoğraf", video="Video", audio="Ses", voice="Sesli mesaj", document="Belge", table="Tablo", list="Liste", paragraph="Paragraf", heading="Bölüm başlığı", footer="Alt bilgi", divider="Ayırıcı", map="Harita", invalid="Geçersiz seçim.", missing_block="Bu blok artık mevcut değil.", choose_action="Bir işlem seç:", send_file="Bir belge gönder.", send_photo="Bir fotoğraf gönder.", send_video="Bir video gönder.", send_audio="Bir ses dosyası gönder.", send_voice="Bir sesli mesaj gönder."),
    "fa": pack(customize="شخصی‌سازی پیام", choose_block="بخشی را که می‌خواهید ویرایش کنید انتخاب کنید:", block_added="بخش با موفقیت اضافه شد.", welcome="به ویرایشگر پیام غنی خوش آمدید.", start_editor="برای شروع پیام جدید /editor را ارسال کنید.", send_message="پیامی را که می‌خواهید شخصی‌سازی کنید ارسال کنید.", unsupported="این نوع پشتیبانی نمی‌شود. متن، رسانه یا Rich Message ارسال کنید.", expired="نشست منقضی شد. برای شروع دوباره /editor را ارسال کنید.", add_block="➕ افزودن بخش", result="✅ نتیجه", create_post="📝 ساخت پست", save_page="💾 ذخیره صفحه", pages="📚 صفحه‌های من", edit="✏️ ویرایش", edit_content="✏️ ویرایش محتوا", delete="🗑 حذف", move="↕️ تغییر جایگاه", back="🔙 بازگشت", preview_block="👁 پیش‌نمایش این بخش", preview_generating="در حال ساخت پیش‌نمایش…", preview_ready="پیش‌نمایش آماده است.", preview_failed="پیش‌نمایش ناموفق بود.", add_buttons="🔘 افزودن دکمه‌ها", buttons_manage="مدیریت دکمه‌های پیام غنی", add="➕ افزودن", remove="➖ حذف", color="🎨 تغییر رنگ", reorder="↕️ تغییر ترتیب", post_settings="تنظیمات پست", send_now="📤 ارسال پست اکنون", select_chat="حداقل یک گفتگو را انتخاب کنید.", details="جزئیات", photo="عکس", video="ویدیو", audio="صدا", voice="پیام صوتی", document="فایل", table="جدول", list="فهرست", paragraph="پاراگراف", heading="عنوان بخش", footer="پاورقی", divider="جداکننده", map="نقشه", invalid="انتخاب نامعتبر است.", missing_block="این بخش دیگر وجود ندارد.", choose_action="یک عملیات انتخاب کنید:", send_file="یک فایل ارسال کنید.", send_photo="یک عکس ارسال کنید.", send_video="یک ویدیو ارسال کنید.", send_audio="یک فایل صوتی ارسال کنید.", send_voice="یک پیام صوتی ارسال کنید."),
    "ku": pack(customize="Peyamê taybet bike", choose_block="Bloka ku dixwazî biguherînî hilbijêre:", block_added="Blok bi serkeftî hate zêdekirin.", welcome="Bi xêr hatî Edîtora Rich Message.", start_editor="Ji bo destpêkirina peyameke nû /editor bişîne.", send_message="Peyama ku dixwazî taybet bikî bişîne.", unsupported="Ev cure nayê piştgirîkirin. Nivîs, medya an Rich Message bişîne.", expired="Danişîn qediya. Ji bo destpêkirina nû /editor bişîne.", add_block="➕ Blok zêde bike", result="✅ Encam", create_post="📝 Weşanê çêbike", save_page="💾 Rûpelê tomar bike", pages="📚 Rûpelên min", edit="✏️ Biguherîne", edit_content="✏️ Naverokê biguherîne", delete="🗑 Jê bibe", move="↕️ Cihê biguherîne", back="🔙 Vegere", preview_block="👁 Pêşdîtina vê blokê", preview_generating="Pêşdîtin tê çêkirin…", preview_ready="Pêşdîtin amade ye.", preview_failed="Pêşdîtin bi ser neket.", add_buttons="🔘 Bişkok zêde bike", buttons_manage="Bişkokên Rich Message birêve bibe", add="➕ Zêde bike", remove="➖ Rake", color="🎨 Rengê biguherîne", reorder="↕️ Rêz bike", post_settings="Mîhengên weşanê", send_now="📤 Niha weşanê bişîne", select_chat="Herî kêm axaftinek hilbijêre.", details="Hûragahî", photo="Wêne", video="Vîdyo", audio="Deng", voice="Peyama dengî", document="Belge", table="Tablo", list="Lîste", paragraph="Paragraf", heading="Sernavê beşê", footer="Binpê", divider="Dabeşker", map="Nexşe", invalid="Hilbijartin ne derbasdar e.", missing_block="Ev blok êdî tune ye.", choose_action="Çalakiyek hilbijêre:", send_file="Belgeyek bişîne.", send_photo="Wêneyek bişîne.", send_video="Vîdyoyek bişîne.", send_audio="Pelê dengî bişîne.", send_voice="Peyameke dengî bişîne."),
    "ur": pack(customize="پیغام کو حسبِ ضرورت بنائیں", choose_block="وہ بلاک منتخب کریں جسے آپ ترمیم کرنا چاہتے ہیں:", block_added="بلاک کامیابی سے شامل ہوگیا۔", welcome="Rich Message Editor میں خوش آمدید۔", start_editor="نیا پیغام شروع کرنے کے لیے /editor بھیجیں۔", send_message="وہ پیغام بھیجیں جسے آپ حسبِ ضرورت بنانا چاہتے ہیں۔", unsupported="یہ قسم معاونت یافتہ نہیں۔ متن، میڈیا یا Rich Message بھیجیں۔", expired="سیشن ختم ہوگیا۔ دوبارہ شروع کرنے کے لیے /editor بھیجیں۔", add_block="➕ بلاک شامل کریں", result="✅ نتیجہ", create_post="📝 پوسٹ بنائیں", save_page="💾 صفحہ محفوظ کریں", pages="📚 میرے صفحات", edit="✏️ ترمیم", edit_content="✏️ مواد میں ترمیم", delete="🗑 حذف", move="↕️ جگہ تبدیل کریں", back="🔙 واپس", preview_block="👁 اس بلاک کا پیش منظر", preview_generating="پیش منظر تیار ہورہا ہے…", preview_ready="پیش منظر تیار ہے۔", preview_failed="پیش منظر ناکام ہوگیا۔", add_buttons="🔘 بٹن شامل کریں", buttons_manage="Rich Message بٹن منظم کریں", add="➕ شامل کریں", remove="➖ ہٹائیں", color="🎨 رنگ بدلیں", reorder="↕️ ترتیب بدلیں", post_settings="پوسٹ کی ترتیبات", send_now="📤 پوسٹ ابھی بھیجیں", select_chat="کم از کم ایک چیٹ منتخب کریں۔", details="تفصیلات", photo="تصویر", video="ویڈیو", audio="آڈیو", voice="صوتی پیغام", document="دستاویز", table="جدول", list="فہرست", paragraph="پیراگراف", heading="حصے کی سرخی", footer="فٹر", divider="تقسیم کنندہ", map="نقشہ", invalid="غلط انتخاب۔", missing_block="یہ بلاک اب موجود نہیں۔", choose_action="ایک عمل منتخب کریں:", send_file="ایک دستاویز بھیجیں۔", send_photo="ایک تصویر بھیجیں۔", send_video="ایک ویڈیو بھیجیں۔", send_audio="ایک آڈیو فائل بھیجیں۔", send_voice="ایک صوتی پیغام بھیجیں۔"),
}

PROFILES = {
    "tr": profile("Rich Message Düzenleyici", "Telegram Rich Message içeriklerini bloklar, medya, listeler, tablolar ve önizlemelerle oluşturun ve düzenleyin.", "Telegram Rich Message oluşturun.", "Yeni Rich Message başlat", "Tüm blokları göster", "Botu aç"),
    "fa": profile("ویرایشگر پیام غنی", "پیام‌های غنی تلگرام را با بلوک‌ها، رسانه، فهرست‌ها، جدول‌ها و پیش‌نمایش ایجاد و ویرایش کنید.", "ساخت و ویرایش پیام غنی تلگرام.", "شروع پیام غنی جدید", "نمایش همه بلوک‌ها", "باز کردن ربات"),
    "ku": profile("Edîtora Rich Message", "Peyamên dewlemend ên Telegram bi blok, medya, lîste, tablo û pêşdîtinan çêbike û biguherîne.", "Rich Message yên Telegram çêbike.", "Rich Message nû dest pê bike", "Hemû blokan nîşan bide", "Botê veke"),
    "ur": profile("Rich Message ایڈیٹر", "Telegram کے Rich Message بلاکس، میڈیا، فہرستوں، جدولوں اور پیش منظر کے ساتھ بنائیں اور ترمیم کریں۔", "Telegram Rich Message بنائیں۔", "نیا Rich Message شروع کریں", "تمام بلاکس دکھائیں", "بوٹ کھولیں"),
}
