import { makeBlock, normalizeBlock, normalizeBlocks, SOURCE_IMPORTED, SOURCE_NATIVE } from 'lib/editor/models';
import { entityRichText } from 'lib/editor/builders';
import { nativeFileData } from 'lib/media';
const NATIVE_TYPE_MAP={voice_note:'voice',section_heading:'heading',block_quotation:'blockquote',pull_quotation:'pullquote'};
function clone(v){ return v==null?v:JSON.parse(JSON.stringify(v)); }
function newBlock(type,position,data,source=SOURCE_IMPORTED){ return makeBlock(type,data,{position,source}); }
function nativeType(kind){ return NATIVE_TYPE_MAP[kind]??(kind==='paragraph'?'text':kind); }
function nativeRawToBlock(raw,position){ const rawType=String(raw?.type??'content'),blockType=nativeType(rawType),data={native_type:rawType,native_data:clone(raw),native:true}; const media=nativeFileData(raw,blockType); if(media) data.file=media; if(blockType==='details'){ data.summary_rich_text=clone(raw.summary??raw.title??'تفاصيل'); data.children=(raw.blocks??[]).map((x,i)=>nativeRawToBlock(x,i)); } else if(['collage','slideshow'].includes(blockType)){ data.children=(raw.blocks??[]).map((x,i)=>nativeRawToBlock(x,i)); data.caption_rich_text=clone(raw.caption?.text??null); data.credit_rich_text=clone(raw.caption?.credit??null); } else if(blockType==='blockquote'){ data.quote_rich_text=(raw.blocks??[]).map(x=>x.text??''); data.credit_rich_text=clone(raw.credit??null); } else if(blockType==='pullquote'){ data.quote_rich_text=clone(raw.text??''); data.credit_rich_text=clone(raw.credit??null); } else if(blockType==='map'){ data.latitude=raw.location?.latitude; data.longitude=raw.location?.longitude; data.zoom=raw.zoom??15; data.width=raw.width??600; data.height=raw.height??400; } else { if(raw.text!=null) data.rich_text=clone(raw.text); if(raw.caption?.text!=null) data.caption_rich_text=clone(raw.caption.text); if(raw.caption?.credit!=null) data.credit_rich_text=clone(raw.caption.credit); if(raw.size!=null) data.size=raw.size; if(raw.language!=null) data.language=raw.language; if(raw.expression!=null) data.text=raw.expression; if(raw.name!=null) data.text=raw.name; if(raw.items!=null) data.items=clone(raw.items); if(raw.cells!=null) data.rows=clone(raw.cells); for(const key of ['is_bordered','is_striped','is_compact','is_open']) if(raw[key]!=null) data[key]=raw[key]; } return newBlock(blockType,position,data,SOURCE_NATIVE); }
function mediaFromMessage(message){ if(Array.isArray(message?.photo)&&message.photo.length) return ['photo',message.photo.at(-1)]; for(const name of ['video','animation','audio','voice','document','sticker','video_note']) if(message?.[name]) return [name,message[name]]; return [null,null]; }
export function messageToBlocks(message,startPosition=0){ if(message?.rich_message?.blocks) return normalizeBlocks(message.rich_message.blocks.map((raw,i)=>nativeRawToBlock(raw,startPosition+i))); const blocks=[]; let position=startPosition; if(typeof message?.text==='string'){ blocks.push(newBlock('text',position,{text:message.text,rich_text:entityRichText(message.text,message.entities??[])})); return normalizeBlocks(blocks); } const [mediaType,file]=mediaFromMessage(message); if(mediaType&&file){ blocks.push(newBlock(mediaType,position,{file:clone(file),has_spoiler:Boolean(message.has_media_spoiler)})); position++; } if(typeof message?.caption==='string') blocks.push(newBlock('caption',position,{text:message.caption,rich_text:entityRichText(message.caption,message.caption_entities??[])})); blocks.forEach(normalizeBlock); return normalizeBlocks(blocks); }
export function messagesToBlocks(messages){ const blocks=[]; for(const message of [...(messages??[])].sort((a,b)=>Number(a.message_id)-Number(b.message_id))) blocks.push(...messageToBlocks(message,blocks.length)); return normalizeBlocks(blocks); }
export function replacementBlock(message,blockType){ const parsed=messageToBlocks(message),wanted=['text','caption','quote'].includes(blockType)?'text':blockType; return parsed.find(x=>x.type===wanted)??null; }
export function replacementData(message,blockType){ const r=replacementBlock(message,blockType); if(!r) return null; const data=clone(r.data); if(blockType==='caption') data.caption=true; return data; }
