import { readState, writeState } from 'lib/storage/state';

function now(){return Math.floor(Date.now()/1000);}
function randomToken(){return (Date.now().toString(16)+Math.floor(Math.random()*1e14).toString(16)).slice(-12);}

export async function rememberManagedChat(userId,chat){const d=await readState('managed_chats',{users:{},panels:{}});d.users??={};d.panels??={};d.users[String(userId)]??={};d.users[String(userId)][String(chat.chat_id)]={chat_id:Number(chat.chat_id),title:String(chat.title??chat.chat_id),type:String(chat.type??'group'),username:chat.username??null,invite_link:chat.invite_link??null,url:chat.url??null};await writeState('managed_chats',d);}
export async function managedChatsForUser(userId){const d=await readState('managed_chats',{users:{}});return Object.values(d.users?.[String(userId)]??{}).filter(x=>x&&typeof x==='object').sort((a,b)=>String(a.title??'').localeCompare(String(b.title??'')));}
export async function removeManagedChat(userId,chatId){const d=await readState('managed_chats',{users:{},panels:{}});delete d.users?.[String(userId)]?.[String(chatId)];if(d.users?.[String(userId)]&&Object.keys(d.users[String(userId)]).length===0)delete d.users[String(userId)];await writeState('managed_chats',d);}
export async function removeManagedChatEverywhere(chatId){const d=await readState('managed_chats',{users:{},panels:{}});for(const chats of Object.values(d.users??{}))if(chats&&typeof chats==='object')delete chats[String(chatId)];await writeState('managed_chats',d);}
export async function rememberPublishPanel(userId,panel){const d=await readState('managed_chats',{users:{},panels:{}});d.panels??={};d.panels[String(userId)]={chat_id:Number(panel.chat_id),message_id:Number(panel.message_id),selected_chat_ids:(panel.selected_chat_ids??[]).map(Number)};await writeState('managed_chats',d);}
export async function publishPanelForUser(userId){const d=await readState('managed_chats',{panels:{}});return d.panels?.[String(userId)]??null;}
export async function clearPublishPanel(userId){const d=await readState('managed_chats',{users:{},panels:{}});delete d.panels?.[String(userId)];await writeState('managed_chats',d);}

export async function rememberGuestMessage(inlineMessageId,chatId,chatType){if(!inlineMessageId)return;const d=await readState('guest_messages',{});d[inlineMessageId]={chat_id:Number(chatId),chat_type:String(chatType),created_at:now()};await writeState('guest_messages',d);}
export async function getGuestMessage(inlineMessageId){const d=await readState('guest_messages',{});return d[inlineMessageId]??null;}

export async function rememberPopup(id,text){const d=await readState('button_popups',{popups:{}});d.popups??={};d.popups[String(id)]=String(text);await writeState('button_popups',d);}
export async function getPopup(id){const d=await readState('button_popups',{popups:{}});return d.popups?.[String(id)]??null;}
export async function removePopup(id){const d=await readState('button_popups',{popups:{}});delete d.popups?.[String(id)];await writeState('button_popups',d);}

export const NAVIGATION_TTL_SECONDS=86400,MAX_NAVIGATION_DEPTH=32;
function navState(token,value){if(!value||!Array.isArray(value.stack))return null;return {token,user_id:Number(value.user_id),stack:value.stack.map(String),external_root:Boolean(value.external_root),get root_page_id(){return this.external_root||!this.stack.length?null:this.stack[0];},get can_go_back(){return this.external_root||this.stack.length>1;},get can_go_home(){return this.stack.length>(this.external_root?1:2);},get is_at_root(){return this.external_root?!this.stack.length:this.stack.length<=1;}};}
async function navDoc(){const d=await readState('page_navigation',{});const cutoff=now()-NAVIGATION_TTL_SECONDS;for(const [k,v] of Object.entries(d))if(Number(v?.updated_at??0)<cutoff)delete d[k];return d;}
export async function navigatePage(userId,sourcePageId,targetPageId,token=null){const d=await navDoc();let current=token?navState(token,d[token]):null,stack,external;if(!current||current.user_id!==Number(userId)){do{token=randomToken();}while(d[token]);stack=sourcePageId?[String(sourcePageId),String(targetPageId)]:[String(targetPageId)];external=!sourcePageId;}else{stack=[...current.stack];external=current.external_root;if(sourcePageId){const i=stack.lastIndexOf(String(sourcePageId));stack=i>=0?stack.slice(0,i+1):[String(sourcePageId)];}if(stack.at(-1)!==String(targetPageId))stack.push(String(targetPageId));if(stack.length>MAX_NAVIGATION_DEPTH)stack=[stack[0],...stack.slice(-(MAX_NAVIGATION_DEPTH-1))];}d[token]={user_id:Number(userId),stack,external_root:external,updated_at:now()};await writeState('page_navigation',d);return navState(token,d[token]);}
export async function navigationBack(token,userId){const d=await navDoc(),current=navState(token,d[token]);if(!current||current.user_id!==Number(userId)||!current.can_go_back){await writeState('page_navigation',d);return null;}const previous=[...current.stack],stack=[...current.stack];if(stack.length)stack.pop();d[token]={...d[token],stack,previous_stack:previous,updated_at:now()};await writeState('page_navigation',d);return navState(token,d[token]);}
export async function navigationHome(token,userId){const d=await navDoc(),current=navState(token,d[token]);await writeState('page_navigation',d);return current&&current.user_id===Number(userId)?current:null;}
export async function commitNavigationBack(token,userId){const d=await navDoc(),current=navState(token,d[token]);if(current?.user_id===Number(userId)){delete d[token].previous_stack;d[token].updated_at=now();await writeState('page_navigation',d);}}
export async function rollbackNavigationBack(token,userId){const d=await navDoc(),current=navState(token,d[token]);if(current?.user_id===Number(userId)&&Array.isArray(d[token].previous_stack)){d[token].stack=d[token].previous_stack;delete d[token].previous_stack;d[token].updated_at=now();await writeState('page_navigation',d);}}
export async function finishNavigation(token){const d=await navDoc();delete d[token];await writeState('page_navigation',d);}
