[package]
name = "rich_core_native"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "rich_core_native"
crate-type = ["cdylib"]

[dependencies]
html-escape = "0.2"
pyo3 = { version = "0.22.6", features = ["extension-module", "abi3-py312"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
