(() => {
 'use strict';
 const $=s=>document.querySelector(s),tg=window.Telegram?.WebApp,init=tg?.initData;
 const errors={registration_closed:'إضافة البوتات مغلقة لحين اكتمال نظام الدفع والتحقق.',license_required:'تحتاج ترخيصاً مستقلاً وسارياً لهذا البوت.',invalid_token:'التوكن غير صحيح أو ملغي.',reserved_bot:'هذا البوت محجوز للنظام.',bot_or_license_already_linked:'البوت أو الترخيص مرتبط مسبقاً.',not_found:'البوت غير متاح لحسابك.',operation_in_progress:'عملية أخرى قيد التنفيذ. حاول بعد قليل.',media_reupload_required:'تعذّر الوصول إلى أحد ملفات الصفحة. أعد رفعه في المحرر واحفظ الصفحة.',media_too_large:'حجم الوسائط يتجاوز حد النقل: ٢٠ ميغابايت للملف و٤٠ للرسالة.',unauthorized:'تعذّر التحقق من حسابك. افتح بوتاتي من تليكرام مجدداً.',rate_limited:'طلبات كثيرة. انتظر دقيقة.',owner_chat_permission_required:'لازم تكون مشرفاً في المجموعة أو القناة.',bot_chat_permission_required:'البوت لا يملك صلاحية إرسال الرسائل هنا.',connection_failed:'تعذّر الاتصال بتليكرام.',invalid_commands:'اكتب أمراً ووصفه في كل سطر: /example وصف الأمر',license_expired:'انتهى الترخيص؛ جدده ثم فعّل البوت.',stale_operation_review:'عملية انقطعت. راجع اتصال البوت ثم أعد تفعيله.',unavailable:'الخدمة غير متاحة أو إعداداتها غير مكتملة.'};
 const states={active:'يعمل',disabled:'متوقف',suspended:'معلّق',needs_relink:'يحتاج توكن جديد'};
 let working=false;
 const notice=text=>{$('#notice').textContent=text;};
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 async function api(body,path='/miniapp/api/managed-bots') {
 const response=await fetch(path,{method:body?'POST':'GET',headers:{'X-Telegram-Init-Data':init,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});
 const data=await response.json();if(!response.ok)throw Error(errors[data.error]||'تعذّرت العملية. حاول مرة ثانية.');return data;
 }
 async function task(fn){if(working)return;working=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message);}finally{working=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 const wait=()=>new Promise(r=>setTimeout(r,1500));
 async function pages(){let data=await api({action:'pages'});for(let i=0;i<30&&data.pending;i++){await wait();data=await api(null,'/miniapp/api/bridge/'+data.request_id);}if(!data.pages)throw Error('تأخر تحميل الصفحات. حاول بعد قليل.');return data.pages;}
 function field(label,type='text',value=''){const wrap=el('label',label),input=el(type==='textarea'?'textarea':type==='select'?'select':'input');if(input.tagName==='INPUT')input.type=type;input.value=value;wrap.append(input);return {wrap,input};}
 function dialog(title,fields,onSave){$('#edit-title').textContent=title;$('#fields').replaceChildren(...fields.map(f=>f.wrap));$('#editor').showModal();$('#edit-form').onsubmit=e=>{e.preventDefault();task(async()=>{await onSave();$('#editor').close();$('#fields').replaceChildren();await refresh();});};}
 const actionButton=(box,label,fn)=>{const b=el('button',label);b.onclick=()=>task(fn);box.append(b);};
 async function refresh(){const data=await api();$('#content').hidden=false;$('#license').replaceChildren(...data.licenses.map(l=>{const o=el('option',l.id+' — '+new Date(l.expires_at).toLocaleDateString('ar-IQ'));o.value=l.id;return o;}));$('#add').hidden=!data.registration_enabled||!data.licenses.length;$('#bots').replaceChildren();
 for(const b of data.bots){const card=el('article'),title=el('h2',b.bot_name||b.bot_username),meta=el('p','@'+b.bot_username+' · '+states[b.status]+' · انتهاء الترخيص: '+(b.expires_at?new Date(b.expires_at).toLocaleDateString('ar-IQ'):'غير متوفر'));meta.className='meta';card.append(title,meta);if(b.last_error)card.append(el('p',errors[b.last_error]||'تعذّرت آخر عملية اتصال. راجع التوكن والصلاحيات.'));if(b.welcome_page_id)card.append(el('p','صفحة الترحيب: '+b.welcome_page_id));const actions=el('div');actions.className='actions';card.append(actions);
 actionButton(actions,'تفعيل',async()=>{const check=await api({action:'activate',id:b.id});if(check.confirmation_required&&confirm(check.external_webhook?'البوت متصل بخدمة أخرى. هل توافق على استبدال Webhook وتشغيله هنا؟':'تفعيل البوت واستقبال رسائله هنا؟')){await api({action:'activate',id:b.id,confirm:true,confirmWebhookTakeover:check.external_webhook});notice('تم تفعيل البوت.');await refresh();}});
 actionButton(actions,'إيقاف',async()=>{if(confirm('إيقاف المعالجة وإزالة اتصالنا مع الحفاظ على الإعدادات؟')){await api({action:'disable',id:b.id,confirm:true});notice('تم إيقاف البوت.');await refresh();}});
 actionButton(actions,'رسالة الترحيب',async()=>{const f=field('النص — يحل محل صفحة الترحيب الغنية','textarea',b.welcome_text||'');f.input.maxLength=3000;dialog('رسالة الترحيب',[f],()=>api({action:'welcome',id:b.id,text:f.input.value}));});
 actionButton(actions,'صفحة الترحيب',async()=>{const list=await pages(),f=field('اختر صفحة محفوظة','select');for(const p of list){const o=el('option',p.title||p.page_id);o.value=p.page_id;f.input.append(o);}dialog('صفحة الترحيب الغنية',[f],async()=>{let data=await api({action:'bind_page',id:b.id,page_id:f.input.value});for(let i=0;i<30&&data.pending;i++){await wait();data=await api({action:'bind_page',id:b.id,page_id:f.input.value,request_id:data.request_id});}if(data.pending)throw Error('تأخر ربط الصفحة. حاول مجدداً.');notice('تم ربط صفحة الترحيب.');});});
 actionButton(actions,'إرسال صفحة',async()=>{const list=await pages(),f=field('الصفحة','select'),chat=field('معرّف الدردشة — حسابك أو مجموعة/قناة أنت مشرف فيها');for(const p of list){const o=el('option',p.title||p.page_id);o.value=p.page_id;f.input.append(o);}dialog('إرسال بهوية البوت',[f,chat],async()=>{if(!confirm('إرسال الصفحة إلى الدردشة المحددة؟'))return;let data=await api({action:'publish',id:b.id,page_id:f.input.value,chat_id:chat.input.value,request_id:crypto.randomUUID()});const jobId=data.job_id;for(let i=0;i<30&&['pending','busy','processing'].includes(data.status);i++){await wait();data=await api({action:'job',id:b.id,job_id:jobId});}if(data.status!=='completed')throw Error(data.status==='uncertain'?'نتيجة الإرسال غير مؤكدة. افحص الدردشة قبل إرسال نسخة أخرى.':errors[data.error_code||data.error]||'الإرسال ما زال قيد المعالجة أو تعذّر. رقم المتابعة: '+jobId);notice('تم إرسال الصفحة.');});});
 actionButton(actions,'عمليات الإرسال',async()=>{const data=await api({action:'jobs',id:b.id});const f=field('آخر ٢٠ عملية','textarea',data.jobs.map(j=>j.job_id+' — '+({completed:'تم',pending:'بانتظار المعالجة',processing:'قيد المعالجة',failed:'فشل',uncertain:'نتيجة غير مؤكدة — افحص الدردشة قبل الإعادة',cancelled:'ملغي'}[j.status]||j.status)+(j.error_code?' · '+(errors[j.error_code]||j.error_code):'')).join('\n'));f.input.readOnly=true;dialog('عمليات الإرسال',[f],async()=>{});});
 actionButton(actions,'الأوامر',async()=>{const f=field('كل سطر: /command وصف أو رد نصي','textarea',JSON.parse(b.commands_json||'[]').filter(c=>!['start','help','admin'].includes(c.command)).map(c=>'/'+c.command+' '+c.description).join('\n'));dialog('إدارة الأوامر',[f],()=>api({action:'commands',id:b.id,commands:f.input.value.split('\n').filter(x=>x.trim()).map(x=>{const [command,...rest]=x.trim().split(/\s+/);return {command,description:rest.join(' ')};})}));});
 actionButton(actions,'تغيير التوكن',async()=>{const f=field('التوكن الجديد للبوت نفسه','password');f.input.autocomplete='off';dialog('تغيير التوكن — يحتاج تفعيل من جديد',[f],async()=>{const token=f.input.value;f.input.value='';await api({action:'rotate_token',id:b.id,token,confirm:true});notice('تم تغيير التوكن. فعّل البوت بعد مراجعة الاتصال.');});});
 actionButton(actions,'إلغاء الربط',async()=>{if(confirm('إلغاء الربط وحذف التوكن المخزن وإلغاء المهام المعلقة؟ لا يحذف هذا البوت من BotFather.')){await api({action:'unlink',id:b.id,confirm:true});notice('تم إلغاء الربط.');await refresh();}});$('#bots').append(card);}
 if(!data.bots.length)notice(data.registration_enabled?'ما عندك بوتات مرتبطة. تحتاج ترخيصاً صالحاً للإضافة.':'إضافة البوتات مغلقة لحين اكتمال الدفع والتحقق.');
 }
 $('#cancel').onclick=()=>{$('#editor').close();$('#fields').replaceChildren();};$('#editor').addEventListener('close',()=>$('#fields').replaceChildren());$('#refresh').onclick=()=>task(refresh);
 $('#register').onsubmit=e=>{e.preventDefault();task(async()=>{const token=$('#token').value;$('#token').value='';await api({action:'register',license_id:$('#license').value,token});notice('تم الربط. راجع هوية البوت ثم فعّله.');await refresh();});};
 if(!init){notice('افتح بوتاتي من داخل تليكرام.');return;}tg.ready();tg.expand?.();task(refresh);
})();
