import { makeBlock } from 'lib/editor/models';
const CODE_LANGUAGE_RE=/^[A-Za-z0-9_+.#-]{1,32}$/;
const LIST_KINDS=new Set(['bullet','numbered','checklist']);
export function newBlock(blockType,data=null){ return makeBlock(blockType,data); }
export function entityRichText(text,entities=[]){ if(!text||!Array.isArray(entities)||!entities.length) return text??''; if([...text].length!==text.length) return text; const chars=[...text], byOffset=new Map(); for(const e of entities){ const start=Number(e.offset??0),length=Number(e.length??0); if(length<=0) continue; if(!byOffset.has(start)) byOffset.set(start,[]); byOffset.get(start).push({...e,end:start+length}); } const render=(start,end)=>{ const out=[]; let i=start; while(i<end){ const c=(byOffset.get(i)??[]).filter(e=>e.end<=end).sort((a,b)=>b.end-a.end); if(c.length){ const e=c[0],inner=render(i,e.end),type=String(e.type??''); let w=inner; const m={bold:'bold',italic:'italic',underline:'underline',strikethrough:'strikethrough',spoiler:'spoiler',code:'code'}; if(m[type]) w={type:m[type],text:inner}; else if(type==='text_link') w={type:'url',text:inner,url:e.url}; else if(type==='text_mention') w={type:'text_mention',text:inner,user:e.user}; else if(type==='custom_emoji') w={type:'custom_emoji',custom_emoji_id:e.custom_emoji_id,alternative_text:chars.slice(i,e.end).join('')}; out.push(w); i=e.end; continue; } out.push(chars[i]); i++; } return out.length===1?out[0]:out; }; return render(0,chars.length); }
export function preformattedData(plain){ let code=String(plain??''),language=null; const lines=code.split(/\r?\n/); if(lines[0]?.startsWith('```')){ const c=lines[0].slice(3).trim(); if(c&&CODE_LANGUAGE_RE.test(c)) language=c; const body=lines.slice(1); if(body.at(-1)?.trim()==='```') body.pop(); code=body.join('\n'); } else if(lines[0]?.toLocaleLowerCase().startsWith('/lang ')){ const c=lines[0].slice(6).trim(); if(CODE_LANGUAGE_RE.test(c)){ language=c; code=lines.slice(1).join('\n'); } } return {text:code,rich_text:code,language}; }
export function listData(plain,kind='bullet'){ const safe=LIST_KINDS.has(kind)?kind:'bullet',items=[]; for(const raw of String(plain??'').split(/\r?\n/)){ let line=raw.trim(); if(!line) continue; let checked=false; if(safe==='checklist'){ const done=line.match(/^(?:\[\s*[xX]\s*\]|✅|☑️?)\s*/), pending=line.match(/^(?:\[\s*\]|⬜|☐)\s*/), marker=done??pending; if(marker){ checked=Boolean(done); line=line.slice(marker[0].length).trim(); } } else if(safe==='numbered') line=line.replace(/^\d+\s*[.)-]\s*/,'').trim(); else line=line.replace(/^[-•\s]+/,'').trim(); if(!line) continue; const item={text:line,rich_text:line}; if(safe==='checklist') Object.assign(item,{has_checkbox:true,is_checked:checked}); if(safe==='numbered') Object.assign(item,{value:items.length+1,type:'1'}); items.push(item); } return {items,kind:safe,text:String(plain??'')}; }
export function tableData(plain){ const rows=String(plain??'').split(/\r?\n/).filter(x=>x.trim()).map(x=>x.split('|').map(y=>y.trim())); const widest=Math.max(1,...rows.map(r=>r.length)); return {rows:rows.map(r=>r.length===1&&widest>1?[{text:r[0],colspan:widest}]:r),text:String(plain??'')}; }
export function textData(message,blockType,{headingSize=2,listKind='bullet'}={}){ const plain=String(message?.text??message?.caption??''),entities=message?.entities??message?.caption_entities??[],rich=entityRichText(plain,entities); if(['paragraph','text'].includes(blockType)) return {text:plain,rich_text:rich}; if(blockType==='heading') return {text:plain,rich_text:rich,size:Math.max(1,Math.min(6,Number(headingSize)||2))}; if(blockType==='preformatted') return preformattedData(plain); if(blockType==='footer') return {text:plain,rich_text:rich}; if(blockType==='mathematical_expression') return {text:plain}; if(blockType==='list') return listData(plain,listKind); if(blockType==='table') return tableData(plain); return {text:plain,rich_text:rich}; }
export function quoteData(message,credit=null){ const plain=String(message?.text??message?.caption??''); return {quote_text:plain,quote_rich_text:entityRichText(plain,message?.entities??message?.caption_entities??[]),credit_rich_text:credit}; }
export function detailsData(summaryRichText,children){ return {summary_rich_text:summaryRichText,children}; }
export function containerData(children){ return {children,caption_rich_text:null,credit_rich_text:null}; }
export function mapData(latitude,longitude){ return {latitude,longitude,zoom:15,width:600,height:400,caption_rich_text:null,credit_rich_text:null}; }
