from __future__ import annotations

from app.lang.catalogs.common import pack, profile

TRANSLATIONS = {
    "hi": pack(customize="संदेश अनुकूलित करें", choose_block="जिस ब्लॉक को संपादित करना है उसे चुनें:", block_added="ब्लॉक सफलतापूर्वक जोड़ा गया।", welcome="Rich Message Editor में आपका स्वागत है।", start_editor="नया संदेश शुरू करने के लिए /editor भेजें।", send_message="जिस संदेश को अनुकूलित करना है उसे भेजें।", unsupported="यह प्रकार समर्थित नहीं है। टेक्स्ट, मीडिया या Rich Message भेजें।", expired="सत्र समाप्त हो गया। फिर से शुरू करने के लिए /editor भेजें।", add_block="➕ ब्लॉक जोड़ें", result="✅ परिणाम", create_post="📝 पोस्ट बनाएँ", save_page="💾 पेज सहेजें", pages="📚 मेरे पेज", edit="✏️ संपादित करें", edit_content="✏️ सामग्री संपादित करें", delete="🗑 हटाएँ", move="↕️ स्थान बदलें", back="🔙 वापस", preview_block="👁 इस ब्लॉक का पूर्वावलोकन", preview_generating="पूर्वावलोकन बनाया जा रहा है…", preview_ready="पूर्वावलोकन तैयार है।", preview_failed="पूर्वावलोकन विफल रहा।", add_buttons="🔘 बटन जोड़ें", buttons_manage="Rich Message बटन प्रबंधित करें", add="➕ जोड़ें", remove="➖ हटाएँ", color="🎨 रंग बदलें", reorder="↕️ क्रम बदलें", post_settings="पोस्ट सेटिंग्स", send_now="📤 पोस्ट अभी भेजें", select_chat="कम से कम एक चैट चुनें।", details="विवरण", photo="फ़ोटो", video="वीडियो", audio="ऑडियो", voice="वॉइस नोट", document="दस्तावेज़", table="तालिका", list="सूची", paragraph="अनुच्छेद", heading="सेक्शन शीर्षक", footer="फ़ुटर", divider="विभाजक", map="मानचित्र", invalid="अमान्य चयन।", missing_block="यह ब्लॉक अब मौजूद नहीं है।", choose_action="एक कार्रवाई चुनें:", send_file="एक दस्तावेज़ भेजें।", send_photo="एक फ़ोटो भेजें।", send_video="एक वीडियो भेजें।", send_audio="एक ऑडियो फ़ाइल भेजें।", send_voice="एक वॉइस नोट भेजें।"),
    "id": pack(customize="Sesuaikan pesan", choose_block="Pilih blok yang ingin diedit:", block_added="Blok berhasil ditambahkan.", welcome="Selamat datang di Rich Message Editor.", start_editor="Kirim /editor untuk memulai pesan baru.", send_message="Kirim pesan yang ingin disesuaikan.", unsupported="Jenis ini belum didukung. Kirim teks, media, atau Rich Message.", expired="Sesi telah berakhir. Kirim /editor untuk memulai lagi.", add_block="➕ Tambah blok", result="✅ Hasil", create_post="📝 Buat posting", save_page="💾 Simpan halaman", pages="📚 Halaman saya", edit="✏️ Edit", edit_content="✏️ Edit konten", delete="🗑 Hapus", move="↕️ Ubah posisi", back="🔙 Kembali", preview_block="👁 Pratinjau blok ini", preview_generating="Membuat pratinjau…", preview_ready="Pratinjau siap.", preview_failed="Pratinjau gagal.", add_buttons="🔘 Tambah tombol", buttons_manage="Kelola tombol Rich Message", add="➕ Tambah", remove="➖ Hapus", color="🎨 Ubah warna", reorder="↕️ Ubah urutan", post_settings="Pengaturan posting", send_now="📤 Kirim posting sekarang", select_chat="Pilih setidaknya satu chat.", details="Detail", photo="Foto", video="Video", audio="Audio", voice="Pesan suara", document="Dokumen", table="Tabel", list="Daftar", paragraph="Paragraf", heading="Judul bagian", footer="Footer", divider="Pemisah", map="Peta", invalid="Pilihan tidak valid.", missing_block="Blok ini sudah tidak ada.", choose_action="Pilih tindakan:", send_file="Kirim dokumen.", send_photo="Kirim foto.", send_video="Kirim video.", send_audio="Kirim file audio.", send_voice="Kirim pesan suara."),
    "ja": pack(customize="メッセージをカスタマイズ", choose_block="編集するブロックを選択してください：", block_added="ブロックを追加しました。", welcome="Rich Message Editor へようこそ。", start_editor="新しいメッセージを作成するには /editor を送信してください。", send_message="カスタマイズするメッセージを送信してください。", unsupported="この種類は未対応です。テキスト、メディア、または Rich Message を送信してください。", expired="セッションの有効期限が切れました。/editor で再開してください。", add_block="➕ ブロックを追加", result="✅ 結果", create_post="📝 投稿を作成", save_page="💾 ページを保存", pages="📚 マイページ", edit="✏️ 編集", edit_content="✏️ 内容を編集", delete="🗑 削除", move="↕️ 位置を変更", back="🔙 戻る", preview_block="👁 このブロックをプレビュー", preview_generating="プレビューを生成中…", preview_ready="プレビューの準備ができました。", preview_failed="プレビューに失敗しました。", add_buttons="🔘 ボタンを追加", buttons_manage="Rich Message のボタンを管理", add="➕ 追加", remove="➖ 削除", color="🎨 色を変更", reorder="↕️ 並べ替え", post_settings="投稿設定", send_now="📤 今すぐ投稿", select_chat="少なくとも1つのチャットを選択してください。", details="詳細", photo="写真", video="動画", audio="音声", voice="ボイスメッセージ", document="ドキュメント", table="表", list="リスト", paragraph="段落", heading="セクション見出し", footer="フッター", divider="区切り", map="地図", invalid="無効な選択です。", missing_block="このブロックはもう存在しません。", choose_action="操作を選択してください：", send_file="ドキュメントを送信してください。", send_photo="写真を送信してください。", send_video="動画を送信してください。", send_audio="音声ファイルを送信してください。", send_voice="ボイスメッセージを送信してください。"),
    "ko": pack(customize="메시지 사용자 지정", choose_block="편집할 블록을 선택하세요:", block_added="블록이 성공적으로 추가되었습니다.", welcome="Rich Message Editor에 오신 것을 환영합니다.", start_editor="새 메시지를 시작하려면 /editor를 보내세요.", send_message="사용자 지정할 메시지를 보내세요.", unsupported="이 유형은 지원되지 않습니다. 텍스트, 미디어 또는 Rich Message를 보내세요.", expired="세션이 만료되었습니다. 다시 시작하려면 /editor를 보내세요.", add_block="➕ 블록 추가", result="✅ 결과", create_post="📝 게시물 만들기", save_page="💾 페이지 저장", pages="📚 내 페이지", edit="✏️ 편집", edit_content="✏️ 내용 편집", delete="🗑 삭제", move="↕️ 위치 변경", back="🔙 뒤로", preview_block="👁 이 블록 미리보기", preview_generating="미리보기를 생성하는 중…", preview_ready="미리보기가 준비되었습니다.", preview_failed="미리보기에 실패했습니다.", add_buttons="🔘 버튼 추가", buttons_manage="Rich Message 버튼 관리", add="➕ 추가", remove="➖ 제거", color="🎨 색상 변경", reorder="↕️ 순서 변경", post_settings="게시물 설정", send_now="📤 지금 게시물 보내기", select_chat="하나 이상의 채팅을 선택하세요.", details="세부정보", photo="사진", video="동영상", audio="오디오", voice="음성 메시지", document="문서", table="표", list="목록", paragraph="문단", heading="섹션 제목", footer="바닥글", divider="구분선", map="지도", invalid="잘못된 선택입니다.", missing_block="이 블록은 더 이상 존재하지 않습니다.", choose_action="작업을 선택하세요:", send_file="문서를 보내세요.", send_photo="사진을 보내세요.", send_video="동영상을 보내세요.", send_audio="오디오 파일을 보내세요.", send_voice="음성 메시지를 보내세요."),
    "vi": pack(customize="Tùy chỉnh tin nhắn", choose_block="Chọn khối bạn muốn chỉnh sửa:", block_added="Đã thêm khối thành công.", welcome="Chào mừng đến với Rich Message Editor.", start_editor="Gửi /editor để bắt đầu tin nhắn mới.", send_message="Gửi tin nhắn bạn muốn tùy chỉnh.", unsupported="Loại này chưa được hỗ trợ. Hãy gửi văn bản, phương tiện hoặc Rich Message.", expired="Phiên đã hết hạn. Gửi /editor để bắt đầu lại.", add_block="➕ Thêm khối", result="✅ Kết quả", create_post="📝 Tạo bài đăng", save_page="💾 Lưu trang", pages="📚 Trang của tôi", edit="✏️ Chỉnh sửa", edit_content="✏️ Chỉnh sửa nội dung", delete="🗑 Xóa", move="↕️ Đổi vị trí", back="🔙 Quay lại", preview_block="👁 Xem trước khối này", preview_generating="Đang tạo bản xem trước…", preview_ready="Bản xem trước đã sẵn sàng.", preview_failed="Xem trước thất bại.", add_buttons="🔘 Thêm nút", buttons_manage="Quản lý nút Rich Message", add="➕ Thêm", remove="➖ Xóa", color="🎨 Đổi màu", reorder="↕️ Sắp xếp lại", post_settings="Cài đặt bài đăng", send_now="📤 Gửi bài đăng ngay", select_chat="Chọn ít nhất một cuộc trò chuyện.", details="Chi tiết", photo="Ảnh", video="Video", audio="Âm thanh", voice="Tin nhắn thoại", document="Tài liệu", table="Bảng", list="Danh sách", paragraph="Đoạn văn", heading="Tiêu đề phần", footer="Chân trang", divider="Dấu phân cách", map="Bản đồ", invalid="Lựa chọn không hợp lệ.", missing_block="Khối này không còn tồn tại.", choose_action="Chọn một thao tác:", send_file="Gửi một tài liệu.", send_photo="Gửi một ảnh.", send_video="Gửi một video.", send_audio="Gửi một tệp âm thanh.", send_voice="Gửi một tin nhắn thoại."),
    "th": pack(customize="ปรับแต่งข้อความ", choose_block="เลือกบล็อกที่ต้องการแก้ไข:", block_added="เพิ่มบล็อกเรียบร้อยแล้ว", welcome="ยินดีต้อนรับสู่ Rich Message Editor", start_editor="ส่ง /editor เพื่อเริ่มข้อความใหม่", send_message="ส่งข้อความที่ต้องการปรับแต่ง", unsupported="ยังไม่รองรับประเภทนี้ กรุณาส่งข้อความ สื่อ หรือ Rich Message", expired="เซสชันหมดอายุ ส่ง /editor เพื่อเริ่มใหม่", add_block="➕ เพิ่มบล็อก", result="✅ ผลลัพธ์", create_post="📝 สร้างโพสต์", save_page="💾 บันทึกหน้า", pages="📚 หน้าของฉัน", edit="✏️ แก้ไข", edit_content="✏️ แก้ไขเนื้อหา", delete="🗑 ลบ", move="↕️ เปลี่ยนตำแหน่ง", back="🔙 กลับ", preview_block="👁 ดูตัวอย่างบล็อกนี้", preview_generating="กำลังสร้างตัวอย่าง…", preview_ready="ตัวอย่างพร้อมแล้ว", preview_failed="สร้างตัวอย่างไม่สำเร็จ", add_buttons="🔘 เพิ่มปุ่ม", buttons_manage="จัดการปุ่ม Rich Message", add="➕ เพิ่ม", remove="➖ ลบ", color="🎨 เปลี่ยนสี", reorder="↕️ จัดลำดับใหม่", post_settings="การตั้งค่าโพสต์", send_now="📤 ส่งโพสต์ตอนนี้", select_chat="เลือกอย่างน้อยหนึ่งแชต", details="รายละเอียด", photo="รูปภาพ", video="วิดีโอ", audio="เสียง", voice="ข้อความเสียง", document="เอกสาร", table="ตาราง", list="รายการ", paragraph="ย่อหน้า", heading="หัวข้อส่วน", footer="ส่วนท้าย", divider="ตัวแบ่ง", map="แผนที่", invalid="การเลือกไม่ถูกต้อง", missing_block="บล็อกนี้ไม่มีอยู่แล้ว", choose_action="เลือกการทำงาน:", send_file="ส่งเอกสาร", send_photo="ส่งรูปภาพ", send_video="ส่งวิดีโอ", send_audio="ส่งไฟล์เสียง", send_voice="ส่งข้อความเสียง"),
}

PROFILES = {
    "hi": profile("Rich Message Editor", "ब्लॉक, मीडिया, सूचियों, तालिकाओं और पूर्वावलोकन के साथ Telegram Rich Message बनाएँ और अनुकूलित करें।", "Telegram Rich Message बनाएँ।", "नया Rich Message शुरू करें", "सभी ब्लॉक दिखाएँ", "बॉट खोलें"),
    "id": profile("Editor Rich Message", "Buat dan sesuaikan Rich Message Telegram dengan blok, media, daftar, tabel, dan pratinjau.", "Buat Rich Message Telegram.", "Mulai Rich Message baru", "Tampilkan semua blok", "Buka bot"),
    "ja": profile("Rich Message エディター", "ブロック、メディア、リスト、表、プレビューを使って Telegram Rich Message を作成・編集します。", "Telegram Rich Message を作成します。", "新しい Rich Message を開始", "すべてのブロックを表示", "ボットを開く"),
    "ko": profile("Rich Message 편집기", "블록, 미디어, 목록, 표, 미리보기를 사용해 Telegram Rich Message를 만들고 편집합니다.", "Telegram Rich Message를 만듭니다.", "새 Rich Message 시작", "모든 블록 보기", "봇 열기"),
    "vi": profile("Trình sửa Rich Message", "Tạo và tùy chỉnh Rich Message Telegram với khối, phương tiện, danh sách, bảng và bản xem trước.", "Tạo Rich Message Telegram.", "Bắt đầu Rich Message mới", "Hiển thị mọi khối", "Mở bot"),
    "th": profile("ตัวแก้ไข Rich Message", "สร้างและปรับแต่ง Rich Message ของ Telegram ด้วยบล็อก สื่อ รายการ ตาราง และตัวอย่าง", "สร้าง Rich Message ของ Telegram", "เริ่ม Rich Message ใหม่", "แสดงทุกบล็อก", "เปิดบอท"),
}
